Laboratorium 1/Models/Birth.cs
namespace Laboratorium_1.Models
{
    public class Birth
    {
        public string? X { get; set; }
        public DateTime Y { get; set; }

        public bool IsValid()
        {
            return X != null && DateTime.Compare(DateTime.Now, Y) >= 0;
        }

       public void Birth1()
        {
            Y = DateTime.;
        }
}

Laboratorium 1/Models/Calculator.cs
using System.Numerics;

namespace Laboratorium_1.Models
{
    public class Calculator
    {
        public enum Operators
        {
            Add, Sub, Mul, Div
        }
        public Operators? Operator { get; set; }
        public double? X { get; set; }
        public double? Y { get; set; }

        public String Op
        {
            get
            {
                switch (Operator)
                {
                    case Operators.Add:
                        return "+";
                    case Operators.Sub:
                        return "-";
                    case Operators.Mul:
                        return "*";
                    case Operators.Div:
                        return "/";
                     default:
                         return "";
                }
            }
        }

        public bool IsValid()
        {
            return Operator != null && X != null && Y != null;
        }

        public double Calculate()
        {
            switch (Operator)
            {
                case Operators.Add:
                    return (double)(X + Y);
                case Operators.Sub:
                    return (double)(X - Y);
                case Operators.Mul:
                    return (double)(X * Y);
                case Operators.Div:
                    return (double)(X / Y);
                default: 
                    return double.NaN;
            }
        }
    }
}

Laboratorium 1/Models/ErrorViewModel.cs
namespace Laboratorium_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium 1/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_1.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }
    }
}

Laboratorium 1/Controllers/CalculatorController.cs
using Laboratorium_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_1.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Result([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
        public IActionResult Form()
        {
            return View();
        }
        
    }
}

Laboratorium 1/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="x">Imie</label>
                    <input class="form-control" type="text" name="x" id="x" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Data urodzenia</label>
                    <input class="form-control" type="date" name="y" id="y" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Przeslij</button>
                </div>
            </form>
        </div>
    </div>
</div>

Laboratorium 1/Views/Birth/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<H3>Czesc @ViewBag.x, masz @ViewBag.wiek lat(a).</H3>

Laboratorium 1/Views/Calculator/Form.cshtml
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="x">Liczba 1</label>
                    <input class="form-control" type="number" name="x" step="0.00001" id="x" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <select name="operator">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Liczba 2</label>
                    <input class="form-control" type="number" name="y" step="0.00001" id="y" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

Laboratorium 1/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X @Model.Op @Model.Y = <br />@Model.Calculate()</H3>

Laboratorium 1/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h3>Application created by Maciej Gatlik</h3>

Laboratorium 1/Views/Home/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p>Wynik obliczeń: @ViewBag.a @ViewBag.op @ViewBag.b = @ViewBag.result </p>

Laboratorium 1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Laboratorium 1/Views/Shared/CustomError.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Błąd kalkulatora: @ViewBag.ErrorMessage</h2>

Laboratorium 1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Birth</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Laboratorium_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>